#ifndef MLIBC_ABIS_YOLK_XATTR_H
#define MLIBC_ABIS_YOLK_XATTR_H

#ifndef __USE_KERNEL_XATTR_DEFS
enum {
	XATTR_CREATE = 1,
#define XATTR_CREATE XATTR_CREATE
	XATTR_REPLACE = 2
#define XATTR_REPLACE XATTR_REPLACE
};
#	define __UAPI_DEF_XATTR 0
#endif

#endif /* MLIBC_ABIS_YOLK_XATTR_H */
